import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.control.TextArea;

public class AgregarController {
	@FXML
	private Button button_agregar;
	@FXML
	private TextArea lbl_notas;
	@FXML
	private TextField lbl_caducidad;
	@FXML
	private TextField lbl_titulo;
	@FXML
	private TextField lbl_autor;
	@FXML
	private TextField lbl_tipo;
	@FXML
	private TextField lbl_publicacion;
	@FXML
	private TextField lbl_codigo;
	@FXML
	private Button menu_buscar;
	@FXML
	private Button menu_consultar;
	@FXML
	private Button menu_agregar;
	@FXML
	private Button menu_modificar;
	@FXML
	private Button menu_eliminar;
	@FXML
	private Button button_login;
	@FXML
	private TextField lbl_editorial;
	@FXML
	private TextField lbl_tomo;
	@FXML
	private TextField lbl_paginas;
	@FXML
	private TextField lbl_precio;

	// Event Listener on Button[#button_agregar].onAction
	@FXML
	public void agregar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#menu_buscar].onAction
	@FXML
	public void menu_buscar(ActionEvent event) throws IOException {
		Parent buscar = FXMLLoader.load(getClass().getResource("Buscar.fxml"));
		
		Scene scene = new Scene(buscar);
		Stage window = (Stage) ((Node)event.getSource()).getScene().getWindow();
		window.setScene(scene);
		window.show();
	}
	// Event Listener on Button[#menu_consultar].onAction
	@FXML
	public void menu_consultar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#menu_agregar].onAction
	@FXML
	public void menu_agregar(ActionEvent event) throws IOException {
		Parent agregar = FXMLLoader.load(getClass().getResource("Agregar.fxml"));
		
		Scene scene = new Scene(agregar);
		Stage window = (Stage) ((Node)event.getSource()).getScene().getWindow();
		window.setScene(scene);
		window.show();
	}
	// Event Listener on Button[#menu_modificar].onAction
	@FXML
	public void menu_modificar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#menu_eliminar].onAction
	@FXML
	public void menu_eliminar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#button_login].onAction
	@FXML
	public void menu_login(ActionEvent event) throws IOException {
		Parent login = FXMLLoader.load(getClass().getResource("Login.fxml"));
		
		Scene scene = new Scene(login);
		Stage window = (Stage) ((Node)event.getSource()).getScene().getWindow();
		window.setScene(scene);
		window.show();
	}
}
